{"uuid": "11837d6b-a387-4bc4-a198-1ce64acb9a20", "children": ["b5ba898b-3e0a-44cd-9308-dae1581193ca", "2ac8a705-9fef-4787-871f-6c7cbafeab69", "5d243bfe-ef7d-4be4-9a30-b496fed3efde", "bc3e46c4-43e9-4bc8-9b27-3bff6a66d606", "af1e27e1-2209-470a-b4a0-cf5a1de08f3d", "2ca809f5-5beb-4eb4-af06-5b5a701a8ee4", "37896ae6-b77b-4f84-8190-fa2db345684d", "630daf17-f7c2-4a05-9fbd-768339f43a1f", "4762b188-632c-4436-8aaf-cbdbb6e7df62", "18a38796-5eb1-44a4-a4f2-49fc7a7abb29", "46be55b7-a086-4b33-8607-0b86fb04f517", "e7f75f61-8862-40aa-b1fd-3dfd79009a53", "3ba5a341-cd7f-4e61-ab2f-796eb79c7b05", "778eedeb-e152-4fc5-853b-365772fd666e", "f6cd5423-d013-45f2-aa07-d096d61d11c8", "23692985-8599-47d3-b7e6-4fd713198584", "c31c4c46-7ad6-4e74-8b4b-c12bf175edfb", "9e5f0f42-252e-45cb-b2e2-d0530d927712", "8c773c64-9581-4dea-a390-44dd67d1c661", "8706d73c-28f8-47e7-b212-7835aeadeeb7", "81aa6177-9f6d-4c55-9a6b-a7684808e2ee", "78e130d5-7a77-4e7c-92ce-4fe0b51c7425", "7f2b7b5b-e735-4464-a0db-1fe61e251aee", "9df64175-7ab1-4284-8020-77bd25c89ac0", "e64e0437-2c47-4650-8fc4-9b0065d8d86a"], "befores": [{"name": "_xunit_setup_class_fixture_Test_multchamet", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Device 832c16a4 was not in the list of connected devices\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Device 832c16a4 was not in the list of connected devices\n    at getResponseForW3CError (C:\\Users\\pgk bqt\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Users\\pgk bqt\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 864, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 785, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\partytencommon\\multparty_star_end.py\", line 17, in setup_class\n    self.audiencedriver=audience_appium_desired()\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\partytencommon\\audience_desired_caps.py\", line 33, in audience_appium_desired\n    driver = webdriver.Remote('http://localhost' + \":\" + str(data['audience_port']) + '/wd/hub', desired_caps2)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 234, in __init__\n    super().__init__(\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 324, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1688378249946, "stop": 1688378270822}], "start": 1688378249946, "stop": 1688378272310}