{"uuid": "ad16cca9-d156-499c-b5b0-79a28f888150", "children": ["704d7825-6165-452b-a350-230df5d01348", "314251e0-1efd-45e7-85c2-d5d9decf8b2b", "c0c61f08-a68f-4fb5-aafd-458cf026c3d6", "123521dc-2a21-47b5-83d4-ac2ced0796a6", "5c8d6ff0-e4c0-465c-ba77-c3ce964152af", "8a74671c-fe73-4733-878f-343a482a2a5b", "851d3b2a-8163-4218-b074-4ce27137170f", "ac56c4da-e9db-42ad-9d06-4a14caf4076f", "afbaa37e-3870-416b-8fde-77cf37056990", "61ea2d40-fc33-4cbb-bcf6-03795a909094", "c797112a-a9ff-475f-b52b-4869013088a7", "d30bd2de-76c7-46d3-aee7-8514735d1209", "7b6fe2bc-772f-4fdd-a4ea-478987a7ac35", "129a83cb-032b-4229-babb-441e42a38ce7", "74935ebd-aa9b-44f3-9e77-b271b5092a56", "67384e14-eace-4ad1-9986-0867d30daa11", "44caf530-d5fc-4376-8041-b6dcc41a816d", "0b1d8713-8463-4dc0-a2e7-3d15bd2fcfe7", "5abb437a-aa65-4beb-8821-4c380b982f1d", "da784b46-15c1-4bc5-9772-15a9ce2876c2", "b2a88bfb-38fc-40e9-9d17-2d24641eb5e9", "d96a6938-beb3-48c4-88ad-8a3c6c3b95df", "e40ffdd3-8fb5-4c58-9831-1fd758b47a8e", "f6bcb425-2d64-4071-9f1c-51c6dfba87d6", "ed5c71bb-6fbe-4bb0-9eb5-38443c6400bd"], "befores": [{"name": "_xunit_setup_class_fixture_Test_multchamet", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Device DKTUT20512001326 was not in the list of connected devices\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Device DKTUT20512001326 was not in the list of connected devices\n    at getResponseForW3CError (C:\\Users\\pgk bqt\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Users\\pgk bqt\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 864, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 785, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\partytencommon\\multparty_star_end.py\", line 11, in setup_class\n    self.anchordriver=anchor_appium_desired()\n                      ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\partytencommon\\anchor_desired_caps.py\", line 33, in anchor_appium_desired\n    driver = webdriver.Remote('http://localhost' + \":\" + str(data['anchor_port']) + '/wd/hub', desired_caps1)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 234, in __init__\n    super().__init__(\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 324, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1688379530343, "stop": 1688379532539}], "start": 1688379530343, "stop": 1688379534051}