{"uuid": "e13b4e8b-0437-4a53-b215-b17f1ff310a0", "children": ["f9e2a646-831b-40e3-b7df-59cae39cf515", "62d8ed4d-ac44-4dbb-8372-319ebd0a955a", "80a484fb-3b12-4714-aa08-ba24b9c32383", "c64d263e-d37b-4f4f-942a-d2b1c464130e", "01d9bf7b-e963-4ff6-a991-e72623c53f10", "58c17970-c1da-47cd-ac44-16ffd0583bb3", "668c82e9-3fa8-457c-9a67-c153594a8091", "413b2d96-0631-4261-83bb-d0550174bb10", "c06768c7-256d-47c6-abe7-0e5d89cdaf82", "a21807ea-c3f5-4f04-8079-8ea9d8fd8214", "c17bd47c-646f-48d0-bca0-612b99303cc4", "c661dd20-7ad3-4175-9379-cc51915f74c8", "3ca9420b-4c39-4f17-8699-4fe5cb9669e8", "f3724c6e-330c-4616-a4c5-1ba56ba404d3", "41918b84-74b3-4cce-861f-8406382c174e", "3250e222-6c15-4ec8-bc54-4d83ed7d14da", "2d523ce9-63ea-4a94-a13c-5815d1caec5b", "06ebcfb0-7829-48b0-8863-871bd6e05a46", "be6022cc-461b-4816-8d86-edf37dc1cfc4", "5e0298bb-488a-49d0-a482-e68d1ad5b0d1", "d5975336-0525-4512-8939-e849f7a92f91", "6207fe5c-7b9a-4564-9efe-71f68b720af1", "0bc7e8fd-85e5-413e-a90e-f4bbe1a33452", "d5335b58-dad2-451d-837c-48291df91bbe", "81371169-9706-417c-a60c-603bc87518cb", "dc8d2e37-f133-45de-a188-8e9823b46c30", "9d100691-b2e9-4348-9e06-00283a24a4f0", "d09562b9-0f38-46dc-a4e6-d8cc621cab46", "970a5913-8af7-4b78-88d0-b97bcf2d44d7", "0e922056-3f5d-4b27-841c-6a22d31419b9", "bba02825-0211-4a4c-82cf-ab4e038ffddf", "b6f0d0f2-339c-4682-8aed-b6101897519d", "90a5c871-7b8d-4de2-9c00-5ef81dc3b269", "e6140d02-6ab8-4911-bbc7-9587416de489", "e647e25d-9667-42ca-a861-abe283d57e6a", "9f23ef28-d054-4774-a9b0-0b6dab07e56d", "d27fd223-4245-4df3-924c-0353f8dd04d3", "e4a9f85b-4f08-48d1-b51c-d31af48949bc"], "befores": [{"name": "_xunit_setup_class_fixture_Test_multchamet", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Device DKTUT20512001326 was not in the list of connected devices\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Device DKTUT20512001326 was not in the list of connected devices\n    at getResponseForW3CError (C:\\Users\\pgk bqt\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Users\\pgk bqt\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 864, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 785, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\partytencommon\\multparty_star_end.py\", line 11, in setup_class\n    self.anchordriver=anchor_appium_desired()\n                      ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\partytencommon\\anchor_desired_caps.py\", line 33, in anchor_appium_desired\n    driver = webdriver.Remote('http://localhost' + \":\" + str(data['anchor_port']) + '/wd/hub', desired_caps1)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 234, in __init__\n    super().__init__(\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 324, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1688372323621, "stop": 1688372325998}], "start": 1688372323621, "stop": 1688372328479}