{"uuid": "e739533d-0338-4623-9070-7a5d698a2bc6", "children": ["4431337f-cc38-4902-8fac-b72f3a7f1ba1", "8823b552-30e4-46c9-9d78-d1b848e06b0f", "1c718506-5607-4019-80a4-9817f0382b4b", "40cdeddc-1306-4852-884c-54dfa924fa67", "5b20d488-301c-48d7-9603-7cd1ef014ade", "cc640bde-6e40-4551-a59e-3ff4bcbfc4e6", "3eb84fa4-dd22-4dbe-b16c-85dabcec886e", "836ac57f-1ca4-4f00-a31c-ea7687a540a9", "47ec91e5-a15e-4f11-ad62-01752f1dc8ea", "7966dd29-f164-48d9-9b87-4c0a4fb27e80", "4b587481-1c77-414e-9ae0-d83534caaf4d", "8fdc721e-8b84-415b-97b9-ab9babab9445", "4c7f3c7d-0a05-498c-bcbf-7cc07ec298c8", "7c55c4d9-2224-4753-8d92-08f9d3ffafd0", "8eb2063f-a380-45b4-bc9a-cd9bb3a192fc", "6592eb98-dbf0-432c-aee5-84d1ae67025d", "760aaac6-8af1-486b-8d05-1aa7d585089d", "90f2ca76-e814-4b6f-a0d4-3d11134f294c", "b1159d91-d389-47b0-823e-88a3fb679088", "88d4be21-0aa5-4696-8142-548a314cbd93", "173fb944-57d3-4163-9b18-4b6063becb66", "bd60b8c6-4b75-4141-9d4c-74d9b3b71fd8", "3c9c6f4f-541f-4350-b48f-f27a1e0d88ae", "0412a5b4-c510-4643-8e87-02ef914bca05", "deb1f0ce-2b02-4da7-89c2-b25139ebf48c"], "befores": [{"name": "_xunit_setup_class_fixture_Test_multchamet", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Device DKTUT20512001326 was not in the list of connected devices\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Device DKTUT20512001326 was not in the list of connected devices\n    at getResponseForW3CError (C:\\Users\\pgk bqt\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Users\\pgk bqt\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 864, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 785, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\partytencommon\\multparty_star_end.py\", line 11, in setup_class\n    self.anchordriver=anchor_appium_desired()\n                      ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\partytencommon\\anchor_desired_caps.py\", line 33, in anchor_appium_desired\n    driver = webdriver.Remote('http://localhost' + \":\" + str(data['anchor_port']) + '/wd/hub', desired_caps1)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 234, in __init__\n    super().__init__(\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 324, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1688379538238, "stop": 1688379540397}], "start": 1688379538238, "stop": 1688379541885}