{"uuid": "e2dbfca6-60fd-4a03-a379-6921ad9cdfa7", "children": ["689be0a8-0cf3-446b-9321-cb533681ba6f"], "befores": [{"name": "_xunit_setup_method_fixture_Test_chamet", "status": "passed", "start": 1686655994262, "stop": 1686656004861}], "afters": [{"name": "_xunit_setup_method_fixture_Test_chamet::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'F:\\\\app\\\\androidsdk\\\\platform-tools\\\\adb.exe -P 5037 -s 832c16a4 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 1'; Command output: error: device unauthorized.\r\nThis adb server's $ADB_VENDOR_KEYS is not set\r\nTry 'adb kill-server' if that seems wrong.\r\nOtherwise check for a confirmation dialog on your device.\r\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'F:\\\\app\\\\androidsdk\\\\platform-tools\\\\adb.exe -P 5037 -s 832c16a4 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 1'; Command output: error: device unauthorized.\r\nThis adb server's $ADB_VENDOR_KEYS is not set\r\nTry 'adb kill-server' if that seems wrong.\r\nOtherwise check for a confirmation dialog on your device.\r\n\n    at getResponseForW3CError (C:\\Users\\pgk bqt\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Users\\pgk bqt\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 918, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 787, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\partyaudience_Start.py\", line 33, in teardown_method\n    self.driver.quit()\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 562, in quit\n    self.execute(Command.QUIT)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 30, in check_response\n    raise wde\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1686656009797, "stop": 1686656011474}], "start": 1686655994262, "stop": 1686656011474}